// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgtptfhlkplnahzehpci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJndHB0Zmhsa3BsbmFoemVocGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMDI5ODEsImV4cCI6MjA1NjY3ODk4MX0.rhXFrgtnfQMfpDue4DvnxqMW59FRbscNp1Nib4VRyIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);